# PortoDash Streamlit Configuration
# Modern dark-accent fintech aesthetic

[theme]
# Base colors - near-black primary with indigo accent
primaryColor = "#6366F1"          # Indigo action color
backgroundColor = "#FFFFFF"       # Pure white background
secondaryBackgroundColor = "#F9FAFB"  # Soft gray card background
textColor = "#1A1A1A"             # Near-black for primary text

# Font
font = "sans-serif"             # Clean sans-serif stack

[server]
# Development settings
headless = false
port = 8501

[browser]
# Gathering usage stats
gatherUsageStats = false
